name: 🚀 Deploy
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install NPM and Build Angular Project
        run: |  
          npm install
          npm run build
      
      # Here is the deployment action
      - name: Upload from output to a remote server via FTP
        uses: modern-dev/ftp-mirror@v2
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "./dist/spy-game"
          remote_dir: "./spy"
          delete: "false"
